project_name: "my_awesome_project"
batch_size: 64
shuffle_train: True,
shuffle_test: True,
pin_memory: False,
learning_rate: 0.001
epochs: 1
dataset: 'CIFAR10'
model: "resnet18_cifar10"
scheduler: "ReduceLROnPlateau"
augmentation: "basic"
step_size: 10
gamma: 0.1
factor: 0.1
patience: 5
optimizer: "Adam"