_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 16
                - 17
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.5
            "8":
                - 3
                - 5
            "12": 0.18.5
            "13": windows-amd64
augmentation:
    value: basic
batch_size:
    value: 64
dataset:
    value: MNIST
epochs:
    value: 1
factor:
    value: 0.1
gamma:
    value: 0.1
learning_rate:
    value: 0.001
model:
    value: LeNet
optimizer:
    value: Adam
patience:
    value: 5
pin_memory:
    value: False,
project_name:
    value: my_awesome_project
scheduler:
    value: ReduceLROnPlateau
shuffle_test:
    value: True,
shuffle_train:
    value: True,
step_size:
    value: 10
